---
title: "Information theory"
author: "Alex Alemi"
bibliography: references.bib
---

Notes from lectures of intro course on information theory for machine learning by [Alex Alemi](https://www.alexalemi.com):

- Lectures: [\[part I\]](https://youtu.be/WsLsEc-p3ww) [\[part II\]](https://youtu.be/hwZU-O0_12g) [\[part III\]](https://youtu.be/NYcJwXhVhuI)

- [\[slides\]](https://docs.google.com/presentation/d/1oSgexQc4hckbb4eWuMQCTplhR-OPRpK-bquW9_G3pbI/present?usp=sharing)

- [\[problem set\]](https://drive.google.com/file/d/1VdFc41xtayn6YY-ZsHlbOBSCEabmNRXs/view?usp=sharing)

- [\[solutions\]](https://drive.google.com/file/d/1jPUhUS5T2rgyx5Dlt74g4_MwX8vrBi2I/view?usp=sharing)

## Introduction

[Information theory](https://en.wikipedia.org/wiki/Information_theory) is a [recent invention](https://en.wikipedia.org/wiki/A_Mathematical_Theory_of_Communication) by [Claude Shannon](https://en.wikipedia.org/wiki/Claude_Shannon), who was primarily concerned with communication [@shannon1948]. We have to thank him for basically all things digital!

Here, we develop information theory from probability theory rather than in the original context of communication (see [curated list of books](https://franknielsen.github.io/Books/CuratedBookLists.html) by [Frank Nielsen](https://franknielsen.github.io/more.html)).

Fundamentally, information theory is about [measures](https://en.wikipedia.org/wiki/Information_theory_and_measure_theory):

- [weight of evidence](https://en.wikipedia.org/wiki/Bayes%27_theorem): measures the "importance" of data for distinguishing between two hypotheses

$$w[x;p,q] \equiv \log \frac{p(x)}{q(x)}$$

- [relative entropy](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence) (a.k.a. Kullback–Leibler (KL) divergence): measures a "distance" between two distributions

$$\mathcal{S}[p;q] \equiv \sum p(x) \log \frac{p(x)}{q(x)}$$

- [entropy](https://en.wikipedia.org/wiki/Entropy_(information_theory)): measures the "complexity" of a distribution

$$\mathcal{S}[p] \equiv - \sum p(x) \log p(x)$$

- [mutual information](https://en.wikipedia.org/wiki/Mutual_information): measures the "complexity" of the association between two variables

$$\mathcal{I}(X;Y) \equiv \sum p(x,y) \log \frac{p(x,y)}{p(x)p(y)}$$

## Weight of evidence

In the beginning, there was Bayes' rule (joint probability/product rule factored/sliced two ways + algebra):

$$P(A,B) = P(A)P(B \mid A) = P(B)P(A \mid B) = P(B, A)$$

$$P(B \mid A) = \frac{P(B) P(A \mid B)}{P(A)}$$

All "frequentist vs. Bayesian, etc." controversies are rooted in the philosophical interpretation of this uncontroversial rule of probability theory when applied to statistical inference:

$$P(H \mid D) = \frac{P(H) P(D \mid H)}{P(D)}$$ where:

$P(H \mid D) = \text{the (posterior) probability of the hypothesis after observing the data}$

$P(H) = \text{the (prior) probability of the hypothesis before observing the data}$

$P(D \mid H) = \text{the probability of the observed data given the hypothesis (a.k.a. the likelihood of the hypothesis given the observed data)}$

$P(D) = \text{the (marginal) probability (a.k.a. evidence or marginal likelihood) of the observed data, computed by averaging over all hypotheses}$

For example, $P(H \mid D) = \frac{P(H) P(D \mid H)}{P(H) P(D \mid H)+ P(\lnot H) P(D \mid \lnot H)}$

The evidence/marginal likelihood is the tricky bit... so, let's get rid of it!

We begin by considering just two hypotheses $H_1$ and $H_2$:

$$\frac{P(H_1 \mid D)}{P(H_2 \mid D)} = \frac{P(H_1)}{P(H_2)} \frac{P(D \mid H_1)}{P(D \mid H_2)}$$

where:

$\frac{P(H_1 \mid D)}{P(H_2 \mid D)} = \text{the posterior odds}$

$\frac{P(H_1)}{P(H_2)} = \text{the prior odds}$

$\frac{P(D \mid H_1)}{P(D \mid H_2)} = \text{the Bayes' factor/likelihood ratio}$

Then, we log both sides:

$$\log \frac{P(H_1 \mid D)}{P(H_2 \mid D)} = \log \Big(\frac{P(H_1)}{P(H_2)} \frac{P(D \mid H_1)}{P(D \mid H_2)} \Big) =  \log \frac{P(H_1)}{P(H_2)} + \log \frac{P(D \mid H_1)}{P(D \mid H_2)}$$

where:

$\log \frac{P(H_1 \mid D)}{P(H_2 \mid D)} = \text{the posterior log odds}$

$\log \frac{P(H_1)}{P(H_2)} = \text{the prior log odds}$

$\log \frac{P(D \mid H_1)}{P(D \mid H_2)} = \text{the weight of evidence}$

The posterior log odds are prior log odds + the **weight of evidence**.

If you don't know what [odds](https://en.wikipedia.org/wiki/Odds) are (in the case of a single event):

$$\text{Odds}(A) = \frac{P(A)}{P(\lnot A)} = \frac{P(A)}{1 - P(A)}$$

For example:

$$P(A) = 0.5 = \frac{1}{2} \rightarrow \text{Odds}(A) = \frac{\frac{1}{2}}{\frac{1}{2}} = 1 = 1 : 1$$

$$P(A) = 0.75 = \frac{3}{4} \rightarrow \text{Odds}(A) = \frac{\frac{3}{4}}{\frac{1}{4}} = 3 = 3 : 1$$

More generally, odds are the ratio of any two probabilities, not necessarily $P(A)$ and $P(\lnot A)$, e.g., $\frac{P(H_1)}{P(H_2)}$.

> We define the logarithm of the likelihood ration as the **information** in data $X = x$ for discrimination in favor of $H_1$ against $H_2$, i.e., the **weight of evidence** for $H_1$ (against $H_2$) given data $X = x$.

### Change of notation

$$\begin{align}
P(X = x \mid P) & \rightarrow p(x) \\
P(X = x \mid Q) & \rightarrow q(x) \\
\end{align}$$

The probability that some variable $X$ takes on a value $x$ given that some model/hypothesis is true.

The weight of evidence is:

$$\log \frac{p(x)}{q(x)}$$

### Units of weight of evidence

$\log_2 : \text{bit, shannon}$

$\log_e : \text{nat}$

$\log_{10} : \text{dit, ban, hartley}$

$10\log_{10} : \text{deciban}$

|          |      |      |      |      |      |      |      |      |      |      |      |      |      |      |
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
| **db**   | 0    | 1    | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    | 10   | 11   | 12   | 13   |
| **bit**  | 0    | ⅓    | ⅔    | 1    | 1⅓   | 1⅔   | 2    | 2⅓   | 2⅔   | 3    | 3⅓   | 3⅔   | 4    | 4⅓   |
| **nat**  | 0.00 | 0.23 | 0.46 | 0.69 | 0.92 | 1.15 | 1.38 | 1.61 | 1.84 | 2.07 | 2.30 | 2.53 | 2.76 | 2.99 |
| **odds** | 1:1  | 5:4  | π:2  | 2:1  | 5:2  | π:1  | 4:1  | 5:1  | 2π:1 | 8:1  | 10:1 | 4π:1 | 16:1 | 20:1 |
| **p**    | 50%  | 56%  | 61%  | 67%  | 72%  | 76%  | 80%  | 83%  | 86%  | 89%  | 91%  | 93%  | 94%  | 95%  |

### Belief-O-Meter

xxx

## Relative entropy

xxx

## Entropy

xxx

## Mutual information

xxx
